# Generated by Django 4.2 on 2023-04-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('cost', models.FloatField()),
                ('costToMake', models.FloatField()),
                ('img', models.TextField()),
                ('manufacturer', models.CharField(max_length=32)),
            ],
        ),
    ]
