# Generated by Django 4.2 on 2023-04-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
