# Generated by Django 4.2 on 2023-04-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies_api', '0002_cookie_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='quantity',
        ),
    ]
