# Generated by Django 4.2 on 2023-04-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies_api', '0004_cookie_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='costToMake',
            new_name='cost_to_make',
        ),
    ]
